/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoatBaseECharts: typeof import('./components/BoatBaseECharts.vue')['default']
    BoatButton: typeof import('@koihe/boat-ui/es')['BoatButton']
    BoatCancelConfirmButton: typeof import('./components/BoatCancelConfirmButton.vue')['default']
    BoatCard: typeof import('./components/BoatCard.vue')['default']
    BoatColorPick: typeof import('./components/BoatColorPick.vue')['default']
    BoatCopyButton: typeof import('./components/BoatCopyButton.vue')['default']
    BoatEchartsPreview: typeof import('./components/BoatEchartsPreview.vue')['default']
    BoatIconButton: typeof import('./components/BoatIconButton.vue')['default']
    BoatIconfont: typeof import('./components/BoatIconfont.vue')['default']
    BoatLayout: typeof import('./components/BoatLayout.vue')['default']
    BoatMenu: typeof import('./components/BoatMenu.vue')['default']
    BoatNoData: typeof import('./components/BoatNoData.vue')['default']
    BoatRotateMenu: typeof import('@koihe/boat-ui/es')['BoatRotateMenu']
    BoatTips: typeof import('./components/BoatTips.vue')['default']
    BoatTitle: typeof import('./components/BoatTitle.vue')['default']
    BoatUpdateModal: typeof import('./components/BoatUpdateModal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ErrorTip: typeof import('./components/ErrorTip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
