// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        BoatBaseECharts: typeof import('./components/BoatBaseECharts.vue')['default'];
        BoatCancelConfirmButton: typeof import('./components/BoatCancelConfirmButton.vue')['default'];
        BoatCard: typeof import('./components/BoatCard.vue')['default'];
        BoatColorPick: typeof import('./components/BoatColorPick.vue')['default'];
        BoatCopyButton: typeof import('./components/BoatCopyButton.vue')['default'];
        BoatIconButton: typeof import('./components/BoatIconButton.vue')['default'];
        BoatIconfont: typeof import('./components/BoatIconfont.vue')['default'];
        BoatMenu: typeof import('./components/BoatMenu.vue')['default'];
        BoatNoData: typeof import('./components/BoatNoData.vue')['default'];
        BoatTitle: typeof import('./components/BoatTitle.vue')['default'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
        ElDialog: typeof import('element-plus/es')['ElDialog'];
        ElDrawer: typeof import('element-plus/es')['ElDrawer'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElInputNumber: typeof import('element-plus/es')['ElInputNumber'];
        ElOption: typeof import('element-plus/es')['ElOption'];
        ElPopover: typeof import('element-plus/es')['ElPopover'];
        ElRadio: typeof import('element-plus/es')['ElRadio'];
        ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
        ElSelect: typeof import('element-plus/es')['ElSelect'];
        ElSwitch: typeof import('element-plus/es')['ElSwitch'];
        ElTooltip: typeof import('element-plus/es')['ElTooltip'];
        ErrorTip: typeof import('./components/ErrorTip.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}
